<?php
return [
   'location' => [
       [
           'id'          => 1,
           'name'        => 'Hà Nội',
           'slug'        => 'ha_noi',
           'description' => 'location4',
           'slug_full'   => 'ha_noi',
           'slug_fix'    => 'ha_noi',
       ],
       [
           'id'          => 2,
           'name'        => 'Thái Bình',
           'slug'        => 'thai_binh',
           'description' => 'location5',
           'slug_full'   => 'thai_binh',
           'slug_fix'    => 'thai_binh',
       ],
       [
           'id'          => 3,
           'name'        => 'Lào Cai',
           'slug'        => 'lao_cai',
           'description' => 'location1',
           'slug_full'   => 'lao_cai',
           'slug_fix'    => 'lao_cai',
       ],
       [
           'id'          => 4,
           'name'        => 'Hải Phòng',
           'slug'        => 'hai_phong',
           'description' => 'location2',
           'slug_full'   => 'hai_phong',
           'slug_fix'    => 'hai_phong',
       ],

       [
           'id'          => 5,
           'name'        => 'Phú Thọ',
           'slug'        => 'phu_tho',
           'description' => 'location3',
           'slug_full'   => 'phu_tho',
           'slug_fix'    => 'phu_tho',
       ],
       [
           'id'          => 6,
           'name'        => 'Thanh Hóa',
           'slug'        => 'thanh_hoa',
           'description' => 'location3',
           'slug_full'   => 'thanh_hoa',
           'slug_fix'    => 'thanh_hoa',
       ],
       [
           'id'          => 7,
           'name'        => 'TP Hồ Chí Minh',
           'slug'        => 'hcm',
           'description' => 'location3',
           'slug_full'   => 'hcm',
           'slug_fix'    => 'hcm',
       ],
       [
           'id'          => 8,
           'name'        => 'Bình Dương',
           'slug'        => 'binh_duong',
           'description' => 'location3',
           'slug_full'   => 'binh_duong',
           'slug_fix'    => 'binh_duong',
       ],
       [
           'id'          => 10,
           'name'        => 'Hà Tĩnh',
           'slug'        => 'ha_tinh',
           'description' => 'location3',
           'slug_full'   => 'ha_tinh',
           'slug_fix'    => 'ha_tinh',
       ],
       [
           'id'          => 11,
           'name'        => 'Đà Nẵng',
           'slug'        => 'da_nang',
           'description' => 'location3',
           'slug_full'   => 'da_nang',
           'slug_fix'    => 'da_nang',
       ],
       [
           'id'          => 12,
           'name'        => 'Cà Mau',
           'slug'        => 'ca_mau',
           'description' => 'location3',
           'slug_full'   => 'ca_mau',
           'slug_fix'    => 'ca_mau',
       ],
   ]
];
